version: '3.8'
services:
  front:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    command: sh -c "cd app && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
